udpated templates

diff --git a/templates/make_lowering.template b/templates/make_lowering.template
--- a/templates/make_lowering.template
+++ b/templates/make_lowering.template
@@ -1,1 +1,88 @@
-${SCRIPTDIR}/make_lowering ${LOWERINGID} ${DIVE_START} ${ON_BOTTOM} ${OFF_BOTTOM} ${DIVE_STOP}
+####################################################################
+# This template builds a script to supercedes the previous
+# "make_lowering" script.
+# 
+# Copies files from <cruise_id>/Vehicle/RawData to the appropriate  
+# subdirectory for the specified lowering.
+#
+# Created 2019/06/01 JWP
+#
+#######################################################################
+
+VEHICLEBASEDIR=${BASEDIR}/${CRUISEID}/Vehicle
+
+LOWERINGDIR=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}
+
+# Reformat the timestrings
+set intime = `echo ${DIVE_START} | awk 'BEGIN{FS=""}{printf "%s%s%s%s-%s%s-%s%s %s%s:%s%s", $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12}'`
+set ontime = `echo ${ON_BOTTOM} | awk 'BEGIN{FS=""}{printf "%s%s%s%s-%s%s-%s%s %s%s:%s%s", $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12}'`
+set offtime = `echo ${OFF_BOTTOM} | awk 'BEGIN{FS=""}{printf "%s%s%s%s-%s%s-%s%s %s%s:%s%s", $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12}'`
+set outtime = `echo ${DIVE_STOP} | awk 'BEGIN{FS=""}{printf "%s%s%s%s-%s%s-%s%s %s%s:%s%s", $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12}'`
+
+if [ ! -d ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID} ]; then
+  echo "ERROR: the directory ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID} does not exist"
+  exit 1
+fi
+
+echo '*****************************************************' > ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/low_stats
+echo ' Lowering name/number:   '${LOWERINGID} >> ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/low_stats
+echo ' Time in water:          '$intime >> ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/low_stats
+echo ' Time on bottom:         '$ontime >> ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/low_stats
+echo ' Time off bottom:        '$offtime >> ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/low_stats
+echo ' Time out of water:      '$outtime >> ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/low_stats
+echo ' '
+echo '*****************************************************' >> ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/low_stats
+echo '*****************************************************'
+echo ' Running make_lowering for lowering '${LOWERINGID}
+echo ' '
+echo ' root directory is:      '${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}
+echo ' '
+cat ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/low_stats
+echo ' '
+echo ' Control C to stop if these values are wrong and you need to reset things.'
+echo ' '
+echo ' Now processing'
+echo ' '
+echo '*****************************************************'
+echo ' '
+
+DATA_DIRS=("ship" "nav" "veh" "csv" "ctd" "ct2" "hfp" "svp" "ctm" "lss" "eh1" "mag" "oos")
+
+for DATA_DIR in ${DATA_DIRS[@]}; do
+
+  if [ -d ./${DATA_DIR} ]; then
+    echo "Processing ${DATA_DIR} files for lowering: ${LOWERINGID}"
+
+    if [ ! -d ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${DATA_DIR} ]; then
+      mkdir ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${DATA_DIR}
+    fi
+  
+    for PREFIX in ${FILE_PREFIXES[@]}; do
+      if [ ! -f ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${DATA_DIR}/${PREFIX}.${DATA_DIR} ]; then
+        echo "WARNING: Could not find file: ${PREFIX}.${DATA_DIR}"
+      else
+        cp -f  ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${DATA_DIR}/${PREFIX}.${DATA_DIR} ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/$DATA_DIR/
+      fi
+    done
+  else
+    echo "No ${DATA_DIR} data"
+  fi
+done
+
+# Process Navest files
+if [ ! -d ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/Navest ]; then
+  mkdir ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/Navest
+fi
+
+NAVEST_SUFFIXES=(".DAT" ".png" "_INI.M")
+
+for SUFFIX in ${NAVEST_SUFFIXES[@]}; do
+  echo "Processing ${SUFFIX} Navest files for lowering: ${LOWERINGID}"
+  for PREFIX in ${FILE_PREFIXES[@]}; do
+    cp -f  ${VEHICLEBASEDIR}/${RAWDIR}/Navest/${PREFIX}*{SUFFIX} ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/Navest/
+  done
+done
+
+cd ${_D}
+
+echo "Done!"
diff --git a/templates/proc_lowering_by_day.template b/templates/proc_lowering_by_day.template
--- a/templates/proc_lowering_by_day.template
+++ b/templates/proc_lowering_by_day.template
@@ -1,6 +1,258 @@
+####################################################################
+# This template builds a script to supercede the previous
+$ "data_parse" and "data_parse_all" scripts.
+# 
+# Creates daily by-type files and copies the appropriate subset of
+# files to the cooresponding subdirectory for the specified lowering.
+#
+# Created 2019/06/01 JWP
+#
+#######################################################################
+
+VEHICLEBASEDIR=${BASEDIR}/${CRUISEID}/Vehicle
+
+if [ ! -d ${VEHICLEBASEDIR} ]; then
+    echo "ERROR: the directory ${VEHICLEBASEDIR} does not exist"
+    exit 1
+fi
+
+parse_data_type() {
+  source=$1
+  type=$2
+  subDir=$3
+  date=$4
+
+  echo "Parsing ${source} files for type ${type}"
+  
+  cd ${VEHICLEBASEDIR}/${RAWDIR}/${date}
+
+  for file in ${date}*.${source}; do
+    echo "Processing = ${file}"
+    file_base="${file%.*}"
+    if [ -f ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type} ]; then
+      echo "Warning: file ${file_base}.${type} already exists.  Skipping."
+      continue
+    else
+      grep ${type} ${file} | grep -v MDEP > ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+      if [ ! -s ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type} ]; then
+        echo "No data found for type ${type}"
+        rm -f ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+      fi
+    fi
+  end
+
+  cd ${_D}
+
+}
+
 for DATE in ${DATES[@]}; do
-	for DATA_TYPE in ${DATA_TYPES[@]}; do
-		echo "${SCRIPTDIR}/data_parse ${BASEDIR} Rawdata Procdata ${CRUISEID} ${DATA_TYPE} ${DATE}"
-#        sleep 5
-	done
+  for DATA_TYPE in ${DATA_TYPES[@]}; do
+    # ${SCRIPTDIR}/data_parse ${VEHICLEBASEDIR} ${RAWDIR} ${PROCDIR} ${CRUISEID} ${DATA_TYPE} ${DATE}
+
+    case ${DATA_TYPE} in
+
+      "ALT")
+        source=VEH
+        type=${DATA_TYPE}
+        subDir=veh
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "CSV")
+        source=${DATA_TYPE}
+        type=${DATA_TYPE}
+        subDir=csv
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+            cat ${SCRIPTDIR}/csvhead.tx ${outfile} > ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}_tmp.${type}
+            mv ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}_tmp.${type} ${outfile}
+        fi
+        ;;
+
+      "CT1")
+        source=VEH
+        type=${DATA_TYPE}
+        subDir=ctd
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "CT2")
+        source=${DATA_TYPE}
+        type=${DATA_TYPE}
+        subDir=ct2
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "CTM")
+        source=${DATA_TYPE}
+        type=${DATA_TYPE}
+        subDir=ctm
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "DEP")
+        source=VEH
+        type=${DATA_TYPE}
+        subDir=veh
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "EH1")
+        source=${DATA_TYPE}
+        type=${DATA_TYPE}
+        subDir=eh1
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+            cat -v ${outfile} | sed 's/\^M/\n/g' >  ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}_tmp.${type}
+            mv ${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}_tmp.${type} ${outfile}
+        fi
+        ;;
+
+      "HFB")
+        source=${DATA_TYPE}
+        type=${DATA_TYPE}
+        subDir=hfp
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "HFP")
+        source=${DATA_TYPE}
+        type=${DATA_TYPE}
+        subDir=hfp
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "HFR")
+        source=${DATA_TYPE}
+        type=${DATA_TYPE}
+        subDir=hfp
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "HMR")
+        source=VEH
+        type=${DATA_TYPE}
+        subDir=mag
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "LSS")
+        source=${DATA_TYPE}
+        type=${DATA_TYPE}
+        subDir=lss
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "OCT")
+        source=VEH
+        type=${DATA_TYPE}
+        subDir=veh
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "OOS")
+        source=${DATA_TYPE}
+        type=${DATA_TYPE}
+        subDir=oos
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "SVP")
+        source=${DATA_TYPE}
+        type=${DATA_TYPE}
+        subDir=svp
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      "SYS")
+        source=VEH
+        type=${DATA_TYPE}
+        subDir=sys
+        date=${DATE}
+        outfile=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}/${subDir}/${file_base}.${type}
+        parse_data_type ${source} ${type} ${subDir} ${date}
+        if [ -f ${outfile} ]; then
+            #here's where you can do additional stuff to the outfile
+        fi
+        ;;
+
+      *)
+        echo "Unknown Datatype: ${DATA_TYPE}"
+        ;;
+
+    esac
+
+    sleep 5
+  done
 done
diff --git a/templates/rsync_cruise_by_day.template b/templates/rsync_cruise_by_day.template
--- a/templates/rsync_cruise_by_day.template
+++ b/templates/rsync_cruise_by_day.template
@@ -1,42 +1,53 @@
-NAVEST_DIR=${CRUISEDIR}/RawData/Navest
+####################################################################
+# This template builds a script to pulls data from the dlog1 and
+# Navest machines to the appropriate raw data directory for the
+# specified cruise.
+#
+# Created 2019/06/01 JWP
+#
+#######################################################################
 
-if [ ! -d ${NAVEST_DIR} ]; then
-    echo "${NAVEST_DIR} doesn't exist- mkdir'ing"
-    mkdir -p ${NAVEST_DIR}
-    mkdir -p ${NAVEST_DIR}/targets
-    mkdir -p ${NAVEST_DIR}/dvlsend
-    mkdir -p ${NAVEST_DIR}/backup
-    mkdir -p ${NAVEST_DIR}/backup/navest_ini
-    mkdir -p ${NAVEST_DIR}/backup/navg_ini
+VEHICLEBASEDIR=${BASEDIR}/${CRUISEID}/Vehicle
+
+NAVEST_DIR=${VEHICLEBASEDIR}/${RAWDIR}/Navest
+
+if [ ! -d ${VEHICLEBASEDIR}/${RAWDIR} ]; then
+  echo "ERROR: the directory ${VEHICLEBASEDIR}/${RAWDIR} does not exist"
+  exit 1
 fi
-
-echo "Getting the target files for cruise $CRUISEID"
-rsync -av jason@198.17.154.225:/home/jason/cruises/$CRUISEID/targets/ ${NAVEST_DIR}/targets
-
-echo "Getting the map files for cruise $CRUISEID"
-rsync -av jason@198.17.154.225:/home/jason/cruises/$CRUISEID/maps/ ${NAVEST_DIR}/maps
 
 for DATE in ${DATES[@]}; do
 
-	year=`echo ${DATE} | awk '{y=substr($1,1,4); print y}'`
-	month=`echo ${DATE} | awk '{m=substr($1,5,2); print m}'`
-	day=`echo ${DATE} | awk '{d=substr($1,7,2); print d}'`
+  year=`echo ${DATE} | awk '{y=substr($1,1,4); print y}'`
+  month=`echo ${DATE} | awk '{m=substr($1,5,2); print m}'`
+  day=`echo ${DATE} | awk '{d=substr($1,7,2); print d}'`
 
-	echo "Processing ${year}-${month}-${day}"
+  echo "Processing ${year}-${month}-${day}"
 
-	DLOG1DESTDIR=${CRUISEDIR}/RawData/${DATE}
+  DLOG1DESTDIR=${VEHICLEBASEDIR}/${RAWDIR}/${DATE}
 
-	if [ ! -d ${DLOG1DESTDIR} ]; then
-	    echo "${DLOG1DESTDIR} doesn't exist- mkdir'ing"
-	    mkdir -p ${DLOG1DESTDIR}
-	fi
+  if [ ! -d ${DLOG1DESTDIR} ]; then
+    echo "${DLOG1DESTDIR} doesn't exist- mkdir'ing"
+    mkdir -p ${DLOG1DESTDIR}
+  fi
 
-	echo "Getting new day=${DATE} files from dlog1 using rsync"
-	echo "Placing them in ${DLOG1DESTDIR}"
-	rsync -avi --Progress data:dsldata1@198.17.154.201:/data/${DATE}* ${DLOG1DESTDIR}
+  echo "Getting files from dlog1 using rsync"
+  echo "Placing them in ${DLOG1DESTDIR}"
+  rsync -avi --Progress data:dsldata1@198.17.154.201:/data/${DATE}* ${DLOG1DESTDIR}
 
-	echo "Getting Navest .DAT files for date ${targetyear}${targetmonth}${targetday}"
-	rsync -avi --Progress jason@198.17.154.225:/data/nav/${year}${month}${day}_* $NAVEST_DIR
-	echo ""
+  echo "Getting .DAT files from Navest using rsync"
+  rsync -avi --Progress jason@198.17.154.225:/data/nav/${year}${month}${day}_* ${NAVEST_DIR}
+  echo ""
 
 done
+
+if [ ! -d ${NAVEST_DIR} ]; then
+  echo "ERROR: the directory ${NAVEST_DIR} does not exist"
+  exit 1
+fi
+
+echo "Getting the target files for cruise ${CRUISEID}"
+rsync -avi --Progress jason@198.17.154.225:/home/jason/cruises/${CRUISEID}/targets/ ${NAVEST_DIR}/targets
+
+echo "Getting the map files for cruise ${CRUISEID}"
+rsync -avi --Progress jason@198.17.154.225:/home/jason/cruises/${CRUISEID}/maps/ ${NAVEST_DIR}/maps
diff --git a/templates/rsync_cruise_data_to_backups.template b/templates/rsync_cruise_data_to_backups.template
--- a/templates/rsync_cruise_data_to_backups.template
+++ b/templates/rsync_cruise_data_to_backups.template
@@ -1,4 +1,17 @@
+#####################################################################
+# This template builds a backup script for making additional copies 
+# of the specified cruise data directory
+#
+# Created 2019/06/01 JWP
+#
+#####################################################################
 
+CRUISEDIR=${BASEDIR}/${CRUISEID}
+
+if [ ! -d ${CRUISEDIR} ]; then
+  echo "ERROR: the directory ${CRUISEDIR} does not exist"
+  exit 1
+fi
 
 # Set the array of destinations to backup the cruise data to
 # Destinations can take the form of:
@@ -9,5 +22,5 @@
 DESTINATIONS = []
 
 for DEST in ${DESTINATIONS[@]}; do
-	rsync -avi --Progress ${CRUISEDIR} DEST
+  rsync -avi --Progress ${CRUISEDIR} ${DEST}
 done
diff --git a/templates/rsync_proc_rename_clips.template b/templates/rsync_proc_rename_clips.template
--- a/templates/rsync_proc_rename_clips.template
+++ b/templates/rsync_proc_rename_clips.template
@@ -1,3 +1,21 @@
+####################################################################
+# This template builds a scfipt to processes the Highlight and
+# KiPro1080 clips.
+# 
+# Needs to be run twice, once for Highlights, once for KiPro1080 
+#  - By default the script will process Highlight (4k) files.              
+#  - Add -2 to process the KiPro1080 (HD) files.
+#
+# See usage message for additional details
+#
+# Created 2019/06/01 JWP
+#
+#######################################################################
+
+VEHICLEBASEDIR=${BASEDIR}/${CRUISEID}/Vehicle
+
+LOWERINGDIR=${VEHICLEBASEDIR}/${PROCDIR}/${CRUISEID}/${LOWERINGID}
+
 KIPRO_4K_DIR="Highlights"
 KIPRO_1080_DIR="KiPro1080"
 VIDEO_FILE_TYPE="*.mov"
@@ -17,48 +35,45 @@ FILE_RENAME_SCRIPT="${DATE_PREFIX}${FILE_RENAME_SCRIPT_SUFFIX}"
 RSYNC_XFER_LOG="${DATE_PREFIX}_rsync_xfer.log"
 TC_METADATA="tcmd.txt"
 
-
 usage(){
 cat <<EOF
 Usage: $0 [-2?] [-s <source_dir>]
-    -s <source_dir> Source directory of clips (if you want this script to copy the files) 
-    -2              These are the 1080HD (2K) clips, the default is 4K
-    -?              Print this statement
+  -s <source_dir> Source directory of clips (if you want this script to copy the files) 
+  -2              These are the 1080HD (2K) clips, the default is 4K
+  -?              Print this statement
 EOF
 }
-
-# printf '#Clip\tStart\tStart\tStart\tDuration\tDuration\tEnd\tEnd\tEnd\tEncoder\n' > $outtxt
-# printf '#Clip,Start,Start,Start,Duration,Duration,End,End,End,Encoder\n' > $outcsv
-
-# printf '#(KiPro)\tDT\tEpoch\tString\tDec\tInt\tDT\tEpoch\tString\tType\n' >> $outtxt
-# printf '#(KiPro),DT,Epoch,String,Dec,Int,DT,Epoch,String,Type\n' >> $outcsv
-
 
 while getopts ":2s:" opt; do
   case $opt in
    2)
-      CLIPS_2K=1
-      CLIPS_TYPE="1080 HD always-on recordings"
-      ;;
+    CLIPS_2K=1
+    CLIPS_TYPE="1080 HD always-on recordings"
+    ;;
    s)
-	  if [ -d ${OPTARG} ]; then
-	    SOURCE_DIR=${OPTARG}
-	  else
-	    echo ""
-	    echo "Source directory: \"${OPTARG}\" doesn't exist" 
-	    echo ""
-	    exit 0
-      fi
-      ;;
-	 
+    if [ -d ${OPTARG} ]; then
+    SOURCE_DIR=${OPTARG}
+    else
+    echo ""
+    echo "Source directory: \"${OPTARG}\" doesn't exist" 
+    echo ""
+    exit 0
+    fi
+    ;;
+   
    \?)
-      usage
-      exit 0
-      ;;
+    usage
+    exit 0
+    ;;
   esac
 done
 
 shift $((OPTIND-1))
+
+if [ ! -d ${LOWERINGDIR} ]; then
+  echo "ERROR: the directory ${LOWERINGDIR} does not exist"
+  exit 1
+fi
 
 if [ ${CLIPS_2K} == 1 ]; then
   DEST_DIR=${LOWERINGDIR}/${KIPRO_1080_DIR}
@@ -70,7 +85,7 @@ INTERMEDIATE_FILES_DIR=${DEST_DIR}/${INTERMEDIATE_DIR_NAME}
 
 echo "-----------------------------------------------------"
 if [ $SOURCE_DIR ]; then
-	echo "Source Dir:" ${SOURCE_DIR}
+  echo "Source Dir:" ${SOURCE_DIR}
 fi
 echo "Destination Dir:" ${DEST_DIR}
 echo "Video Clip Type:" ${CLIPS_TYPE}
@@ -82,18 +97,18 @@ read -p "Continue? (Y/N): " confirm && [[ $confirm == [Yy] || $confirm == [Yy][E
 
 
 if [ ! -d ${DEST_DIR} ]; then
-	read -p "Destination directory not found. Create it? (Y/N): " confirm && [[ $confirm == [Yy] || $confirm == [Yy][Ee][Ss] ]] || exit 0
-	mkdir -p ${DEST_DIR}
-	if [ ! -d ${DEST_DIR} ]; then
-		echo "Unable to create destination directory... quitting"
-		exit 1
-	fi
+  read -p "Destination directory not found. Create it? (Y/N): " confirm && [[ $confirm == [Yy] || $confirm == [Yy][Ee][Ss] ]] || exit 0
+  mkdir -p ${DEST_DIR}
+  if [ ! -d ${DEST_DIR} ]; then
+    echo "Unable to create destination directory... quitting"
+    exit 1
+  fi
 fi
 
 if [ ${SOURCE_DIR} ]; then
-	echo "Copying files..."
-	rsync -aiv --log-file=${INTERMEDIATE_FILES_DIR}/${RSYNC_XFER_LOG} --include="${VIDEO_FILE_TYPE}" --exclude="*" ${SOURCE_DIR}/ $DEST_DIR/ 
-	echo "Done"
+  echo "Copying files..."
+  rsync -aiv --log-file=${INTERMEDIATE_FILES_DIR}/${RSYNC_XFER_LOG} --include="${VIDEO_FILE_TYPE}" --exclude="*" ${SOURCE_DIR}/ $DEST_DIR/ 
+  echo "Done"
 fi
 
 find -f ${DEST_DIR}/*.mov &> /dev/null || echo "No files to process"; echo "Quitting..."; exit 0
@@ -111,169 +126,165 @@ printf '#!/bin/bash\n' > ${INTERMEDIATE_FILES_DIR}/${FILE_RENAME_SCRIPT}
 FILE_COUNT=0
 for inclip in ${DEST_DIR}/*.mov; do
 
-	# Clear away a file from previous processing, if it exists.
-	if [ -e ${INTERMEDIATE_FILES_DIR}/${TC_METADATA} ]; then
-		rm ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}
-	fi
+  # Clear away a file from previous processing, if it exists.
+  if [ -e ${INTERMEDIATE_FILES_DIR}/${TC_METADATA} ]; then
+    rm ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}
+  fi
 
-	echo "Processing $inclip"
+  echo "Processing $inclip"
 
-	# Get the clip name for later use
-	cn=`basename $inclip`
+  # Get the clip name for later use
+  cn=`basename $inclip`
 
-	# Spawn ffprobe from the ffmpeg suite. ffprobe extracts the metadata of the clip, which is then written to a file.
-	ffprobe -show_streams:tcmd $inclip >& ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}
+  # Spawn ffprobe from the ffmpeg suite. ffprobe extracts the metadata of the clip, which is then written to a file.
+  ${SCRIPTDIR}/ffprobe -show_streams:tcmd $inclip >& ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}
 
-	# echo "TC_METADATA"
-	# cat ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}
-	# grep timecode
+  # Pull lines from the file and extract date and time from them.
 
-	# Pull lines from the file and extract date and time from them.
+  tcstr=`grep timecode ${INTERMEDIATE_FILES_DIR}/${TC_METADATA} | tail -1`
+  # echo "tcstr: ${tcstr}"
 
-	tcstr=`grep timecode ${INTERMEDIATE_FILES_DIR}/${TC_METADATA} | tail -1`
-	# echo "tcstr: ${tcstr}"
+  if [[ $tcstr =~ ^TAG:timecode=([[:digit:]][[:digit:]]):([[:digit:]][[:digit:]]):([[:digit:]][[:digit:]]):[[:digit:]][[:digit:]] ]]; then
+    tchr=`echo ${tcstr} | cut -c 14-15`
+    tcmi=`echo ${tcstr} | cut -c 17-18`
+    tcse=`echo ${tcstr} | cut -c 20-21`
 
-	if [[ $tcstr =~ ^TAG:timecode=([[:digit:]][[:digit:]]):([[:digit:]][[:digit:]]):([[:digit:]][[:digit:]]):[[:digit:]][[:digit:]] ]]; then
-	    tchr=`echo ${tcstr} | cut -c 14-15`
-	    tcmi=`echo ${tcstr} | cut -c 17-18`
-	    tcse=`echo ${tcstr} | cut -c 20-21`
+    # echo ${tchr}:${tcmi}:${tcse}
+    # fr = ${BASH_REMATCH[4]}
 
-	    # echo ${tchr}:${tcmi}:${tcse}
-	    # fr = ${BASH_REMATCH[4]}
+    tchms=$(IFS= ; echo "${BASH_REMATCH[*]:1:3}")
+    # echo "tchms: ${tchms}"
 
-	    tchms=$(IFS= ; echo "${BASH_REMATCH[*]:1:3}")
-	    # echo "tchms: ${tchms}"
+  fi
 
-	fi
+  # Get the date from the creation time. Don't use hour minute second because
+  # creation_time is likely set from device system time, and it is almost
+  # certainly less accurate than our NTP-disciplined timecode generator.
+  # In fact, I don't like getting date from this source but it's the only source
+  # we have.
 
-	# Get the date from the creation time. Don't use hour minute second because
-	# creation_time is likely set from device system time, and it is almost
-	# certainly less accurate than our NTP-disciplined timecode generator.
-	# In fact, I don't like getting date from this source but it's the only source
-	# we have.
+  # It appears that the video creation time is given last, and also give sthe
+  # time the file is closed. Since that could happen that day after the recording
+  # is started, get both dates. If it proves necessary, the end date can be used
+  # against the calculation of clip end time from start plus duration.
 
-	# It appears that the video creation time is given last, and also give sthe
-	# time the file is closed. Since that could happen that day after the recording
-	# is started, get both dates. If it proves necessary, the end date can be used
-	# against the calculation of clip end time from start plus duration.
+  ctstart=`grep TAG\:creation_time ${INTERMEDIATE_FILES_DIR}/${TC_METADATA} | head -1`
+  #TAG:creation_time=2018-09-16T11:18:53.000000Z
+  # echo "ctstart: ${ctstart}"
 
-	ctstart=`grep TAG\:creation_time ${INTERMEDIATE_FILES_DIR}/${TC_METADATA} | head -1`
-	#TAG:creation_time=2018-09-16T11:18:53.000000Z
-	# echo "ctstart: ${ctstart}"
+  if [[ $ctstart =~ ^TAG:creation_time=[[:digit:]][[:digit:]][[:digit:]][[:digit:]]-[[:digit:]][[:digit:]]-[[:digit:]][[:digit:]]T[[:digit:]][[:digit:]]:[[:digit:]][[:digit:]]:[[:digit:]][[:digit:]].[[:digit:]][[:digit:]][[:digit:]][[:digit:]][[:digit:]][[:digit:]]Z ]]; then
+     byr=`echo ${ctstart} | cut -c 19-22`
+     bmo=`echo ${ctstart} | cut -c 24-25`
+     bdy=`echo ${ctstart} | cut -c 27-28`
 
-	if [[ $ctstart =~ ^TAG:creation_time=[[:digit:]][[:digit:]][[:digit:]][[:digit:]]-[[:digit:]][[:digit:]]-[[:digit:]][[:digit:]]T[[:digit:]][[:digit:]]:[[:digit:]][[:digit:]]:[[:digit:]][[:digit:]].[[:digit:]][[:digit:]][[:digit:]][[:digit:]][[:digit:]][[:digit:]]Z ]]; then
-	   byr=`echo ${ctstart} | cut -c 19-22`
-	   bmo=`echo ${ctstart} | cut -c 24-25`
-	   bdy=`echo ${ctstart} | cut -c 27-28`
+     ctstart_ymd=$(IFS= ; echo "${BASH_REMATCH[*]:1:3}")
+  #   echo $ctstart_ymd
+  else
+     echo "Problem extracting clip creation time" 
+  fi
 
-	   ctstart_ymd=$(IFS= ; echo "${BASH_REMATCH[*]:1:3}")
-	#   echo $ctstart_ymd
-	else
-	   echo "Problem extracting clip creation time" 
-	fi
+  ctstop=`grep creation_time ${INTERMEDIATE_FILES_DIR}/${TC_METADATA} | tail -1`
+  #TAG:creation_time=2018-09-16T11:18:53.000000Z
+  # echo "ctstop: ${ctstop}"
 
-	ctstop=`grep creation_time ${INTERMEDIATE_FILES_DIR}/${TC_METADATA} | tail -1`
-	#TAG:creation_time=2018-09-16T11:18:53.000000Z
-	# echo "ctstop: ${ctstop}"
+  if [[ $ctstop =~ ^TAG:creation_time=[[:digit:]][[:digit:]][[:digit:]][[:digit:]]-[[:digit:]][[:digit:]]-[[:digit:]][[:digit:]]T[[:digit:]][[:digit:]]:[[:digit:]][[:digit:]]:[[:digit:]][[:digit:]].[[:digit:]][[:digit:]][[:digit:]][[:digit:]][[:digit:]][[:digit:]]Z ]]; then
+     eyr=`echo ${ctstop} | cut -c 19-22`
+     emo=`echo ${ctstart} | cut -c 24-25`
+     edy=`echo ${ctstart} | cut -c 27-28`
 
-	if [[ $ctstop =~ ^TAG:creation_time=[[:digit:]][[:digit:]][[:digit:]][[:digit:]]-[[:digit:]][[:digit:]]-[[:digit:]][[:digit:]]T[[:digit:]][[:digit:]]:[[:digit:]][[:digit:]]:[[:digit:]][[:digit:]].[[:digit:]][[:digit:]][[:digit:]][[:digit:]][[:digit:]][[:digit:]]Z ]]; then
-	   eyr=`echo ${ctstop} | cut -c 19-22`
-	   emo=`echo ${ctstart} | cut -c 24-25`
-	   edy=`echo ${ctstart} | cut -c 27-28`
+     ctstop_ymd=$(IFS= ; echo "${BASH_REMATCH[*]:1:3}")
+  #   echo $ctstop_ymd
+  else
+     echo "Problem extracting video creation time" 
+  fi
 
-	   ctstop_ymd=$(IFS= ; echo "${BASH_REMATCH[*]:1:3}")
-	#   echo $ctstop_ymd
-	else
-	   echo "Problem extracting video creation time" 
-	fi
+  # Get clip duration in seconds
 
-	# Get clip duration in seconds
+  dur=`grep Duration ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}`
+  #  Duration: 00:00:08.27, start: 0.000000, bitrate: 16622 kb/s
+  # echo "dur: ${dur}"
 
-	dur=`grep Duration ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}`
-	#  Duration: 00:00:08.27, start: 0.000000, bitrate: 16622 kb/s
-	# echo "dur: ${dur}"
+  if [[ $dur =~ ^[[:space:]][[:space:]]Duration:[[:space:]][[:digit:]][[:digit:]]:[[:digit:]][[:digit:]]:[[:digit:]][[:digit:]].[[:digit:]][[:digit:]].* ]]; then
+     dhr=`echo ${dur} | cut -c 11-12`
+     dmi=`echo ${dur} | cut -c 14-15`
+     dse=`echo ${dur} | cut -c 17-21`
 
-	if [[ $dur =~ ^[[:space:]][[:space:]]Duration:[[:space:]][[:digit:]][[:digit:]]:[[:digit:]][[:digit:]]:[[:digit:]][[:digit:]].[[:digit:]][[:digit:]].* ]]; then
-	   dhr=`echo ${dur} | cut -c 11-12`
-	   dmi=`echo ${dur} | cut -c 14-15`
-	   dse=`echo ${dur} | cut -c 17-21`
+     # echo "$dhr $dmi $dse"
+  else
+     echo "Problem extracting duration"
+  fi
 
-	   # echo "$dhr $dmi $dse"
-	else
-	   echo "Problem extracting duration"
-	fi
+  # Convert duration to seconds. Calculate both floating pt and integer
+  # seconds. FP for accuracy and integer because 'date' can't make use
+  # of the decimal portion of seconds.
 
-	# Convert duration to seconds. Calculate both floating pt and integer
-	# seconds. FP for accuracy and integer because 'date' can't make use
-	# of the decimal portion of seconds.
+  # Use a regexp to pull integer seconds from decimal seconds
+  # echo "dse: $dse"
+  if [[ $dse =~ ([[:digit:]][[:digit:]]).[[:digit:]][[:digit:]] ]]; then
+     dsei=${BASH_REMATCH[1]}
+     dsei=$(echo "$dsei 0" | perl -MList::Util=sum -alne 'print sum @F')
+  else
+     echo "Problem converting decimal seconds $dse to integer seconds"
+  fi
 
-	# Use a regexp to pull integer seconds from decimal seconds
-	# echo "dse: $dse"
-	if [[ $dse =~ ([[:digit:]][[:digit:]]).[[:digit:]][[:digit:]] ]]; then
-	   dsei=${BASH_REMATCH[1]}
-	   dsei=$(echo "$dsei 0" | perl -MList::Util=sum -alne 'print sum @F')
-	else
-	   echo "Problem converting decimal seconds $dse to integer seconds"
-	fi
+  # 2017/01/25 SJM sometimes a number is prepended with a '0' char after parsing.
+  # This can be confused as an octal or hex number. To enforce that it's decimal,
+  # one can prepend "10#" to the string representing the number.
 
-	# 2017/01/25 SJM sometimes a number is prepended with a '0' char after parsing.
-	# This can be confused as an octal or hex number. To enforce that it's decimal,
-	# one can prepend "10#" to the string representing the number.
+  dhr2secs=$((10#$dhr * 3600))
+  dmi2secs=$((10#$dmi * 60))
+  dhr_dmi_secs=$((dhr2secs + dmi2secs))
+  dsecsi=$((dhr_dmi_secs + dsei))
+  dsecsf=$(echo "$dhr_dmi_secs $dse" | perl -MList::Util=sum -alne 'print sum @F')
+  echo "Clip duration is $dsecsf seconds."
+  echo "Will use $dsecsi seconds to compute clip end datetime and to create filename."
+    
+  # Convert clip start time to unix epoch seconds. MacOSX date command has
+  # different invocation format than linux.
+  datestr=$(printf '%s-%s-%s %s:%s:%s' "$byr" "$bmo" "$bdy" "$tchr" "$tcmi" "$tcse")
+  #echo $datestr
+  bsecs=$(date -j -f "%Y-%m-%d %H:%M:%S" "$datestr" "+%s")
+  bstr1=$(date -j -f "%Y-%m-%d %H:%M:%S" "$datestr" "+%Y/%m/%d %H:%M:%S")
+  bstr2=$(date -j -f "%Y-%m-%d %H:%M:%S" "$datestr" "+%Y%m%d%H%M%S")
 
-	dhr2secs=$((10#$dhr * 3600))
-	dmi2secs=$((10#$dmi * 60))
-	dhr_dmi_secs=$((dhr2secs + dmi2secs))
-	dsecsi=$((dhr_dmi_secs + dsei))
-	dsecsf=$(echo "$dhr_dmi_secs $dse" | perl -MList::Util=sum -alne 'print sum @F')
-	echo "Clip duration is $dsecsf seconds."
-	echo "Will use $dsecsi seconds to compute clip end datetime and to create filename."
-	  
-	# Convert clip start time to unix epoch seconds. MacOSX date command has
-	# different invocation format than linux.
-	datestr=$(printf '%s-%s-%s %s:%s:%s' "$byr" "$bmo" "$bdy" "$tchr" "$tcmi" "$tcse")
-	#echo $datestr
-	bsecs=$(date -j -f "%Y-%m-%d %H:%M:%S" "$datestr" "+%s")
-	bstr1=$(date -j -f "%Y-%m-%d %H:%M:%S" "$datestr" "+%Y/%m/%d %H:%M:%S")
-	bstr2=$(date -j -f "%Y-%m-%d %H:%M:%S" "$datestr" "+%Y%m%d%H%M%S")
+  echo "Clip start time is $bstr1, $bsecs unix seconds"
 
-	echo "Clip start time is $bstr1, $bsecs unix seconds"
+  # Now add clip start time and duration seconds, convert back to a date string 
+  #date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s"   # man page example
+  esecs=$((bsecs + dsecsi))
+  # echo "Clip end epoch secs is $esecs"
+  estr1=$(date -j -r $esecs "+%Y/%m/%d %H:%M:%S")
+  estr2=$(date -j -r $esecs "+%Y%m%d%H%M%S")
 
-	# Now add clip start time and duration seconds, convert back to a date string 
-	#date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s"   # man page example
-	esecs=$((bsecs + dsecsi))
-	# echo "Clip end epoch secs is $esecs"
-	estr1=$(date -j -r $esecs "+%Y/%m/%d %H:%M:%S")
-	estr2=$(date -j -r $esecs "+%Y%m%d%H%M%S")
+  echo "Clip end time is $estr1, $esecs unix seconds"
 
-	echo "Clip end time is $estr1, $esecs unix seconds"
+  ################## Output section ###################
+  #
+  # Create a table for use in building the final metadata collection.
 
-	################## Output section ###################
-	#
-	# Create a table for use in building the final metadata collection.
+  # Pull the codec from the clips metyadata fork
+  encgr=`grep TAG\:encoder ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}`
 
-	# Pull the codec from the clips metyadata fork
-	encgr=`grep TAG\:encoder ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}`
+  if [[ $encgr =~ ProRes ]]; then
 
-	if [[ $encgr =~ ProRes ]]; then
+     if [[ $encgr =~ LT ]]; then
+       enc="ProRes422LT"
+     else
+       enc="ProRes422"
+     fi
+  else
+    echo "Unknown encoding"
+  fi
 
-	   if [[ $encgr =~ LT ]]; then
-	       enc="ProRes422LT"
-	   else
-	       enc="ProRes422"
-	   fi
-	else
-	  echo "Unknown encoding"
-	fi
+  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$cn" "$bstr1" "$bsecs" "$bstr2" "$dsecsf" "$dsecsi" "$estr1" "$esecs" "$estr2" "$enc" >> ${INTERMEDIATE_FILES_DIR}/${OUTPUT_BATCH_LIST_TXT}
+  printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' "$cn" "$bstr1" "$bsecs" "$bstr2" "$dsecsf" "$dsecsi" "$estr1" "$esecs" "$estr2" "$enc" >> ${INTERMEDIATE_FILES_DIR}/${OUTPUT_BATCH_LIST_CSV}
 
-	printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$cn" "$bstr1" "$bsecs" "$bstr2" "$dsecsf" "$dsecsi" "$estr1" "$esecs" "$estr2" "$enc" >> ${INTERMEDIATE_FILES_DIR}/${OUTPUT_BATCH_LIST_TXT}
-	printf '%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n' "$cn" "$bstr1" "$bsecs" "$bstr2" "$dsecsf" "$dsecsi" "$estr1" "$esecs" "$estr2" "$enc" >> ${INTERMEDIATE_FILES_DIR}/${OUTPUT_BATCH_LIST_CSV}
+  NEW_FILENAME="${LOWERING}_${bstr2}-${estr2}.mov"
+  if [ ${cn} != ${NEW_FILENAME} && ${cn} != "*.mov" ]; then 
+    printf 'mv -v ../%s ../%s\n' "$cn" "$NEW_FILENAME" >> ${INTERMEDIATE_FILES_DIR}/${FILE_RENAME_SCRIPT}
+  fi
 
-	NEW_FILENAME="${LOWERING}_${bstr2}-${estr2}.mov"
-	if [ ${cn} != ${NEW_FILENAME} && ${cn} != "*.mov" ]; then 
-		printf 'mv -v ../%s ../%s\n' "$cn" "$NEW_FILENAME" >> ${INTERMEDIATE_FILES_DIR}/${FILE_RENAME_SCRIPT}
-	fi
-
-	FILE_COUNT=$((${FILE_COUNT}+1))
+  FILE_COUNT=$((${FILE_COUNT}+1))
 done
 
 echo "Processed ${FILE_COUNT} file(s)."
@@ -282,7 +293,7 @@ chmod +x ${INTERMEDIATE_FILES_DIR}/${FILE_RENAME_SCRIPT}
 
 # Clear away a file from previous processing, if it exists.
 if [ -e ${INTERMEDIATE_FILES_DIR}/${TC_METADATA} ]; then
-	rm ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}
+  rm ${INTERMEDIATE_FILES_DIR}/${TC_METADATA}
 fi
 
 ln -sf ${INTERMEDIATE_FILES_DIR}/${OUTPUT_BATCH_LIST_TXT} ${INTERMEDIATE_FILES_DIR}/latest${OUTPUT_BATCH_LIST_TXT_SUFFIX}
