added template to copy last hour's worth of data.

diff --git a/templates/rsync_cruise_by_day.template b/templates/rsync_cruise_by_day.template
--- a/templates/rsync_cruise_by_day.template
+++ b/templates/rsync_cruise_by_day.template
@@ -13,18 +13,37 @@ VEHICLEBASEDIR=${BASEDIR}/${CRUISEID}/Vehicle
 # Navest directory within the raw data data directory
 NAVESTDIR=${VEHICLEBASEDIR}/${RAWDIR}/Navest
 
-# Verify the raw data directory exists before proceeding
-if [ ! -d ${VEHICLEBASEDIR}/${RAWDIR} ]; then
-  echo "ERROR: the directory ${VEHICLEBASEDIR}/${RAWDIR} does not exist"
+# H264 directory within the cruise data directory
+H264RECORDINGDIR=${BASEDIR}/H264Recordings
+
+# TIFgrabs directory within the cruise data directory
+TIFGRABDIR=${BASEDIR}/TIFgrabs
+
+# Verify the dlog destination directory exists before proceeding
+if [ ! -d ${DLOG1DESTDIR} ]; then
+  echo "ERROR: the directory ${DLOG1DESTDIR} does not exist"
   exit 1
 fi
 
-# Verify the Navest subdirectory within the raw data directory exists
-# before proceeding
+# Verify the Navest destination directory exists before proceeding
 if [ ! -d ${NAVESTDIR} ]; then
   echo "ERROR: the directory ${NAVESTDIR} does not exist"
   exit 1
 fi
+
+# Verify the h264recordings destination directory exists before proceeding
+if [ ! -d ${H264RECORDINGDIR} ]; then
+  echo "ERROR: the directory ${H264RECORDINGDIR} does not exist"
+  exit 1
+fi
+
+# Verify the tifgrab destination directory exists before proceeding
+if [ ! -d ${TIFGRABDIR} ]; then
+  echo "ERROR: the directory ${TIFGRABDIR} does not exist"
+  exit 1
+fi
+
+echo "Currently just performing a dry-run... remember to remove the -n flag from the rsync commands to actually copy files"
 
 # Loop through all the specified dates for the cruise
 for DATE in ${DATES[@]}; do
@@ -36,30 +55,29 @@ for DATE in ${DATES[@]}; do
 
   echo "Processing ${year}-${month}-${day}"
 
-  # Set the destination directory
-  DLOG1DESTDIR=${VEHICLEBASEDIR}/${RAWDIR}/${DATE}
+  echo "Pulling data files from dlog1 to ${DLOG1DESTDIR} using rsync"
+  rsync -avin -P data:dsl!data1@198.17.154.201:/data/${DATE} ${DLOG1DESTDIR}
 
-  # Create teh destination directory if it does not exist
-  if [ ! -d ${DLOG1DESTDIR} ]; then
-    echo "Creating ${DLOG1DESTDIR}"
-    mkdir ${DLOG1DESTDIR}
-  fi
+  echo "Pulling *.DAT files from Navest to ${NAVESTDIR} using rsync"
+  rsync -avin -P data:dsl!data1@198.17.154.225:/data/nav/${DATE}_*.DAT ${NAVESTDIR}
+  echo ""
 
-  echo "Retrieving data files from dlog1 using rsync"
-  echo "Placing data files in the ${DLOG1DESTDIR} directory"
-  rsync -avi --Progress data:dsldata1@198.17.154.201:/data/${DATE}/* ${DLOG1DESTDIR}
-
-  echo "Getting .DAT files from Navest using rsync"
-  echo "Placing data files in the ${NAVESTDIR} directory"
-  rsync -avi --Progress jason@198.17.154.225:/data/nav/${year}${month}${day}_* ${NAVESTDIR}
+  echo "Pulling files from rec1 using rsync"
+  rsync -avin -P data:dsl!data1@198.17.154.189:/data/capture_${DATE} ${TIFGRABDIR}
   echo ""
 
 done
 
 echo "Getting target files from Navest using rsync"
 echo "Placing data files in the ${NAVESTDIR}/targets directory"
-rsync -avi --Progress jason@198.17.154.225:/home/jason/cruises/${CRUISEID}/targets/ ${NAVESTDIR}/targets
+rsync -avin -P jason:dsl!jason@198.17.154.225:/home/jason/cruises/${CRUISEID}/targets/ ${NAVESTDIR}/targets
 
 echo "Getting map files from Navest using rsync"
 echo "Placing data files in the ${NAVESTDIR}/maps directory"
-rsync -avi --Progress jason@198.17.154.225:/home/jason/cruises/${CRUISEID}/maps/ ${NAVESTDIR}/maps
+rsync -avin -P jason:dsl!jason@198.17.154.225:/home/jason/cruises/${CRUISEID}/maps/ ${NAVESTDIR}/maps
+
+echo "Getting video files from rec1 using rsync"
+echo "Placing data files in the ${H264RECORDINGDIR} directory"
+rsync -avin -P installer:dsl!installer@198.17.154.189:/home/installer/src/CamDisplayStable201710/ ${H264RECORDINGDIR}
+
+echo "done!"
